version: 2.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-beta'
before_build:
- cmd: nuget restore
build:
  project: Cinegy.Telemetry.sln
  publish_nuget: true
  verbosity: minimal
after_build:
- cmd: >-
    7z a Cinegy.Telemetry-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.Telemetry\bin
    
    appveyor PushArtifact Cinegy.Telemetry-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip
deploy:
- provider: NuGet
  api_key:
    secure: lL1w5Wlk0xkOdYPAYSG2JzQTjVO34MI6xqsNmAUcT6R5OTNRI+hcbJJx5Rqm6gRE
  skip_symbols: true