version: 4.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  project: Cinegy.Telemetry.sln
  publish_nuget: true
  verbosity: minimal
after_build:
- cmd: >-
    7z a Cinegy.Telemetry-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.Telemetry\bin
    
    appveyor PushArtifact Cinegy.Telemetry-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip
deploy:
- provider: NuGet
  api_key:
    secure: tMCS1lvz6Py0b8ydbFKWP62gYQPJMJtb0K049OqObIonopypWe/t/sTH/xsyRZL8
  skip_symbols: false